name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  bump-version:
    name: Bump Extension Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install npm packages
      run: npm ci

    - name: Setup Git
      run: |
        git config user.name 'levrotech'
        git config user.email 'hi.levrotech@tutanota.com'
        git config gpg.format ssh
        git config user.signingKey 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEvuzzXcQ3j2I77wzh2TdesYyCM8rZmkAh8ObO2iqVx5 hi.levrotech@tutanota.com'

    - name: Bump version
      run: npm version ${{ github.event.inputs.version }} --sign-git-tag

    - name: Push latest version
      run: git push origin main --follow-tags